#!/usr/bin/env node
//
// Fusion Stats Collector — run hourly via cron to build history.json
//
// Usage:
//   node collect.js              # single run, appends to history.json
//   crontab: 0 * * * * cd /path/to/fusionstats && node collect.js
//

const fs = require('fs');
const path = require('path');

const MORPHO_API = 'https://api.morpho.org/graphql';
const HISTORY_FILE = path.join(__dirname, 'history.json');
const LOGS_FILE = path.join(__dirname, 'logs.json');
const VAULTS_FILE = path.join(__dirname, 'vaults.json');
const HOURLY_WINDOW_MS = 7 * 24 * 3600 * 1000; // keep hourly data for 7 days
const MAX_DAILY_ENTRIES = 365; // keep up to 1 year of daily averages
const MAX_LOG_ENTRIES = 500; // keep last 500 log entries

// Fallback vault addresses if vaults.json is unavailable
const FALLBACK_VAULTS = [
  '0xb8a451107a9f87fde481d4d686247d6e43ed715e',
  '0x3b3bdaa4462851621818d2cebc835e077587147a',
  '0x604117f0c94561231060f56cd2ddd16245d434c5',
  '0xd36f53497507e948df9f277cf8c3ececb09a1c1d',
  '0xbfa9d6ec0e04b6691fcae5f8b48838c3918ec117',
  '0x43a32d4f6c582f281c52393f8f9e5ace1d4a1e68',
  '0x63103375659d0aa94e9f35df15be01a3dd1ae9c0',
  '0xe9385eff3f937fcb0f0085da9a3f53d6c2b4fb5f',
  '0xb0f56bb0bf13ee05fef8cd2d8df5ffdfcac7a74f',
  '0xf6cd9e8415162c8fb3c52676c7ca68812a34f76e',
  '0x6f66b845604dad6e80b2a1472e6cacbbe66a8c40',
  '0xe47358eae04719f3cf7025e95d0ad202e68bd9b2',
  '0xc50b2d51fd1e2ac67a9c09eaf63c24ea2465c64b',
  '0xe48cdd5ecec5aa53e630a7b4df12f79067b68dac',
  '0x20e934c725b6703f0ac696f1689008057db9ac44',
  '0xef53663bb775a51181f04d590f88fc38d6bd5751',
  '0xad685fec2066d7f5436f5804882998ba79725706',
  '0x87428d886f43068a44d7bdeef106d3c42e1d6f23',
  '0x9824dcdac89f208bf8b5cb5c4dc41f04a0878607',
  '0x60e36a79c3d21120350e39b5ea59ae26b75ae74c',
  '0x0b45a1e71a8a09f5d382fed27202d50ed983aaf3',
  '0xc2a119ea6de75e4b1451330321cb2474eb8d82d4',
  '0xdab31950ddcc814c49e6bbd5153dd2062e44f368',
];

// Load vaults from vaults.json (generated by collect-vaults.js), fallback to hardcoded list
function loadFusionVaults() {
  try {
    const data = JSON.parse(fs.readFileSync(VAULTS_FILE, 'utf8'));
    if (data.vaults && data.vaults.length > 0) {
      console.log(`Loaded ${data.vaults.length} vaults from vaults.json`);
      return data.vaults.map(v => v.address);
    }
  } catch (e) {
    console.warn(`Warning: Could not load vaults.json (${e.message})`);
  }
  console.log(`Using fallback vault list (${FALLBACK_VAULTS.length} vaults)`);
  return FALLBACK_VAULTS;
}

async function gql(query) {
  const res = await fetch(MORPHO_API, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  const json = await res.json();
  if (json.errors) throw new Error(json.errors[0].message);
  return json.data;
}

async function fetchTotalLoans() {
  const data = await gql(`{
    markets(
      first: 1000
      orderBy: BorrowAssetsUsd
      orderDirection: Desc
      where: { chainId_in: [1], listed: true }
    ) {
      items { state { borrowAssetsUsd } }
      pageInfo { count countTotal }
    }
  }`);
  return data.markets.items.reduce((s, m) => s + (m.state?.borrowAssetsUsd || 0), 0);
}

async function fetchVaultPositions(address) {
  const res = await fetch(MORPHO_API, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `{
        userByAddress(chainId: 1, address: "${address}") {
          marketPositions {
            state {
              borrowAssetsUsd
              collateralUsd
            }
          }
        }
      }`
    }),
  });
  const json = await res.json();
  if (json.errors) {
    console.log(`  ${address.slice(0, 10)}...: API error — ${json.errors[0]?.message}`);
    return { borrowed: 0, collateral: 0 };
  }
  const user = json.data?.userByAddress;
  if (!user?.marketPositions?.length) return { borrowed: 0, collateral: 0 };
  const borrowed = user.marketPositions.reduce((s, p) =>
    s + (p.state?.borrowAssetsUsd || p.borrowAssetsUsd || 0), 0);
  const collateral = user.marketPositions.reduce((s, p) =>
    s + (p.state?.collateralUsd || 0), 0);
  return { borrowed, collateral };
}

function appendLog(entry) {
  let logs = [];
  try { logs = JSON.parse(fs.readFileSync(LOGS_FILE, 'utf8')); } catch { }
  logs.push({ ...entry, timestamp: new Date().toISOString() });
  if (logs.length > MAX_LOG_ENTRIES) logs = logs.slice(-MAX_LOG_ENTRIES);
  fs.writeFileSync(LOGS_FILE, JSON.stringify(logs, null, 2));
}

async function collect() {
  const FUSION_VAULTS = loadFusionVaults();

  const runStart = Date.now();
  const logEntry = { level: 'info', event: 'collect', errors: [], warnings: [] };
  console.log(`[${new Date().toISOString()}] Collecting Fusion stats...`);

  // Fetch total loans
  let totalLoans = 0;
  try {
    totalLoans = await fetchTotalLoans();
    logEntry.totalLoans = totalLoans;
    console.log(`  Total Morpho loans: $${(totalLoans / 1e6).toFixed(2)}M`);
  } catch (err) {
    logEntry.level = 'error';
    logEntry.errors.push({ step: 'fetchTotalLoans', message: err.message });
    console.error(`  ERROR fetching total loans: ${err.message}`);
    appendLog(logEntry);
    throw err;
  }

  // Fetch all vault positions in batches of 7
  let fusionBorrowed = 0;
  let fusionCollateral = 0;
  let activeCount = 0;
  const vaultErrors = [];
  for (let i = 0; i < FUSION_VAULTS.length; i += 7) {
    const batch = FUSION_VAULTS.slice(i, i + 7);
    const results = await Promise.all(batch.map(async (a) => {
      try {
        return await fetchVaultPositions(a);
      } catch (err) {
        vaultErrors.push({ vault: a, message: err.message });
        return { borrowed: 0, collateral: 0 };
      }
    }));
    for (const r of results) {
      fusionBorrowed += r.borrowed;
      fusionCollateral += r.collateral;
      if (r.borrowed > 0) activeCount++;
    }
  }

  if (vaultErrors.length > 0) {
    logEntry.warnings.push(...vaultErrors.map(e => ({ step: 'fetchVaultPositions', ...e })));
    if (vaultErrors.length > FUSION_VAULTS.length / 2) {
      logEntry.level = 'warn';
    }
  }

  const sharePercent = totalLoans > 0 ? (fusionBorrowed / totalLoans * 100) : 0;

  logEntry.fusionBorrowed = fusionBorrowed;
  logEntry.fusionCollateral = fusionCollateral;
  logEntry.sharePercent = sharePercent;
  logEntry.activeVaults = activeCount;
  logEntry.totalVaults = FUSION_VAULTS.length;
  logEntry.vaultErrors = vaultErrors.length;
  logEntry.durationMs = Date.now() - runStart;

  console.log(`  Fusion borrowed: $${(fusionBorrowed / 1e6).toFixed(2)}M`);
  console.log(`  Fusion collateral: $${(fusionCollateral / 1e6).toFixed(2)}M`);
  console.log(`  Active vaults: ${activeCount}/${FUSION_VAULTS.length}`);
  console.log(`  Share: ${sharePercent.toFixed(2)}%`);

  // Read existing history
  let history = [];
  try {
    history = JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'));
  } catch (e) { /* first run */ }

  // Deduplicate: skip if last entry is < 45 min old (handles 30-min cron redundancy)
  const MIN_INTERVAL_MS = 45 * 60 * 1000;
  if (history.length > 0) {
    const lastTs = new Date(history[history.length - 1].timestamp).getTime();
    if (Date.now() - lastTs < MIN_INTERVAL_MS) {
      console.log(`  Skipping — last entry is ${Math.round((Date.now() - lastTs) / 60000)}min old (< 45min)`);
      logEntry.event = 'collect_skipped';
      logEntry.reason = 'dedup';
      appendLog(logEntry);
      return;
    }
  }

  // Append new data point
  history.push({
    timestamp: new Date().toISOString(),
    totalLoans,
    fusionBorrowed,
    fusionCollateral,
    sharePercent,
    vaultCount: FUSION_VAULTS.length,
  });

  // Compact: entries older than 7 days get averaged into daily snapshots
  const cutoff = Date.now() - HOURLY_WINDOW_MS;
  const recent = [];
  const oldByDay = {};
  for (const entry of history) {
    if (new Date(entry.timestamp).getTime() >= cutoff) {
      recent.push(entry);
    } else {
      const day = entry.timestamp.slice(0, 10); // YYYY-MM-DD
      if (!oldByDay[day]) oldByDay[day] = [];
      oldByDay[day].push(entry);
    }
  }
  // Average old entries per day
  const dailyEntries = Object.entries(oldByDay).sort().map(([day, entries]) => {
    const avg = (field) => entries.reduce((s, e) => s + (e[field] || 0), 0) / entries.length;
    return {
      timestamp: day + 'T12:00:00.000Z',
      totalLoans: avg('totalLoans'),
      fusionBorrowed: avg('fusionBorrowed'),
      fusionCollateral: avg('fusionCollateral'),
      sharePercent: avg('sharePercent'),
      vaultCount: entries[entries.length - 1].vaultCount,
    };
  });
  // Trim daily to max
  const trimmedDaily = dailyEntries.length > MAX_DAILY_ENTRIES
    ? dailyEntries.slice(dailyEntries.length - MAX_DAILY_ENTRIES)
    : dailyEntries;
  history = [...trimmedDaily, ...recent];

  fs.writeFileSync(HISTORY_FILE, JSON.stringify(history, null, 2));
  console.log(`  Saved to ${HISTORY_FILE} (${history.length} entries)`);

  logEntry.historyEntries = history.length;
  appendLog(logEntry);
  console.log(`  Log appended to ${LOGS_FILE}`);
}

collect().catch(err => {
  console.error('Collection failed:', err.message);
  appendLog({ level: 'error', event: 'collect_crash', message: err.message, stack: err.stack });
  process.exit(1);
});
