#!/usr/bin/env node
//
// Fusion Stats Collector — run hourly via cron to build history.json
//
// Usage:
//   node collect.js              # single run, appends to history.json
//   crontab: 0 * * * * cd /path/to/fusionstats && node collect.js
//

const fs = require('fs');
const path = require('path');

const MORPHO_API = 'https://api.morpho.org/graphql';
const HISTORY_FILE = path.join(__dirname, 'history.json');
const LOGS_FILE = path.join(__dirname, 'logs.json');
const VAULTS_FILE = path.join(__dirname, 'vaults.json');
const HOURLY_WINDOW_MS = 7 * 24 * 3600 * 1000; // keep hourly data for 7 days
const MAX_DAILY_ENTRIES = 365; // keep up to 1 year of daily averages
const MAX_LOG_ENTRIES = 500; // keep last 500 log entries

// Load vaults from vaults.json (generated by collect-vaults.js)
function loadFusionVaults() {
  try {
    const data = JSON.parse(fs.readFileSync(VAULTS_FILE, 'utf8'));
    console.log(`Loaded ${data.vaults.length} vaults from vaults.json`);
    return data.vaults.map(v => v.address);
  } catch (e) {
    console.warn(`Warning: Could not load vaults.json (${e.message}). No vaults to query.`);
    return [];
  }
}

async function gql(query) {
  const res = await fetch(MORPHO_API, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  const json = await res.json();
  if (json.errors) throw new Error(json.errors[0].message);
  return json.data;
}

async function fetchTotalLoans() {
  const data = await gql(`{
    markets(
      first: 1000
      orderBy: BorrowAssetsUsd
      orderDirection: Desc
      where: { chainId_in: [1], whitelisted: true }
    ) {
      items { state { borrowAssetsUsd } }
      pageInfo { count countTotal }
    }
  }`);
  return data.markets.items.reduce((s, m) => s + (m.state?.borrowAssetsUsd || 0), 0);
}

async function fetchVaultPositions(address) {
  const res = await fetch(MORPHO_API, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `{
        userByAddress(chainId: 1, address: "${address}") {
          marketPositions {
            borrowAssetsUsd
            supplyAssetsUsd
            state {
              borrowAssetsUsd
              collateralUsd
            }
          }
        }
      }`
    }),
  });
  const json = await res.json();
  if (json.errors) {
    console.log(`  ${address.slice(0, 10)}...: API error — ${json.errors[0]?.message}`);
    return { borrowed: 0, collateral: 0 };
  }
  const user = json.data?.userByAddress;
  if (!user?.marketPositions?.length) return { borrowed: 0, collateral: 0 };
  const borrowed = user.marketPositions.reduce((s, p) =>
    s + (p.state?.borrowAssetsUsd || p.borrowAssetsUsd || 0), 0);
  const collateral = user.marketPositions.reduce((s, p) =>
    s + (p.state?.collateralUsd || 0), 0);
  return { borrowed, collateral };
}

function appendLog(entry) {
  let logs = [];
  try { logs = JSON.parse(fs.readFileSync(LOGS_FILE, 'utf8')); } catch { }
  logs.push({ ...entry, timestamp: new Date().toISOString() });
  if (logs.length > MAX_LOG_ENTRIES) logs = logs.slice(-MAX_LOG_ENTRIES);
  fs.writeFileSync(LOGS_FILE, JSON.stringify(logs, null, 2));
}

async function collect() {
  const FUSION_VAULTS = loadFusionVaults();
  if (FUSION_VAULTS.length === 0) {
    console.log('No vaults found. Run collect-vaults.js first to discover vaults.');
    return;
  }

  const runStart = Date.now();
  const logEntry = { level: 'info', event: 'collect', errors: [], warnings: [] };
  console.log(`[${new Date().toISOString()}] Collecting Fusion stats...`);

  // Fetch total loans
  let totalLoans = 0;
  try {
    totalLoans = await fetchTotalLoans();
    logEntry.totalLoans = totalLoans;
    console.log(`  Total Morpho loans: $${(totalLoans / 1e6).toFixed(2)}M`);
  } catch (err) {
    logEntry.level = 'error';
    logEntry.errors.push({ step: 'fetchTotalLoans', message: err.message });
    console.error(`  ERROR fetching total loans: ${err.message}`);
    appendLog(logEntry);
    throw err;
  }

  // Fetch all vault positions in batches of 7
  let fusionBorrowed = 0;
  let fusionCollateral = 0;
  let activeCount = 0;
  const vaultErrors = [];
  for (let i = 0; i < FUSION_VAULTS.length; i += 7) {
    const batch = FUSION_VAULTS.slice(i, i + 7);
    const results = await Promise.all(batch.map(async (a) => {
      try {
        return await fetchVaultPositions(a);
      } catch (err) {
        vaultErrors.push({ vault: a, message: err.message });
        return { borrowed: 0, collateral: 0 };
      }
    }));
    for (const r of results) {
      fusionBorrowed += r.borrowed;
      fusionCollateral += r.collateral;
      if (r.borrowed > 0) activeCount++;
    }
  }

  if (vaultErrors.length > 0) {
    logEntry.warnings.push(...vaultErrors.map(e => ({ step: 'fetchVaultPositions', ...e })));
    if (vaultErrors.length > FUSION_VAULTS.length / 2) {
      logEntry.level = 'warn';
    }
  }

  const sharePercent = totalLoans > 0 ? (fusionBorrowed / totalLoans * 100) : 0;

  logEntry.fusionBorrowed = fusionBorrowed;
  logEntry.fusionCollateral = fusionCollateral;
  logEntry.sharePercent = sharePercent;
  logEntry.activeVaults = activeCount;
  logEntry.totalVaults = FUSION_VAULTS.length;
  logEntry.vaultErrors = vaultErrors.length;
  logEntry.durationMs = Date.now() - runStart;

  console.log(`  Fusion borrowed: $${(fusionBorrowed / 1e6).toFixed(2)}M`);
  console.log(`  Fusion collateral: $${(fusionCollateral / 1e6).toFixed(2)}M`);
  console.log(`  Active vaults: ${activeCount}/${FUSION_VAULTS.length}`);
  console.log(`  Share: ${sharePercent.toFixed(2)}%`);

  // Read existing history
  let history = [];
  try {
    history = JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'));
  } catch (e) { /* first run */ }

  // Deduplicate: skip if last entry is < 45 min old (handles 30-min cron redundancy)
  const MIN_INTERVAL_MS = 45 * 60 * 1000;
  if (history.length > 0) {
    const lastTs = new Date(history[history.length - 1].timestamp).getTime();
    if (Date.now() - lastTs < MIN_INTERVAL_MS) {
      console.log(`  Skipping — last entry is ${Math.round((Date.now() - lastTs) / 60000)}min old (< 45min)`);
      logEntry.event = 'collect_skipped';
      logEntry.reason = 'dedup';
      appendLog(logEntry);
      return;
    }
  }

  // Append new data point
  history.push({
    timestamp: new Date().toISOString(),
    totalLoans,
    fusionBorrowed,
    fusionCollateral,
    sharePercent,
    vaultCount: FUSION_VAULTS.length,
  });

  // Compact: entries older than 7 days get averaged into daily snapshots
  const cutoff = Date.now() - HOURLY_WINDOW_MS;
  const recent = [];
  const oldByDay = {};
  for (const entry of history) {
    if (new Date(entry.timestamp).getTime() >= cutoff) {
      recent.push(entry);
    } else {
      const day = entry.timestamp.slice(0, 10); // YYYY-MM-DD
      if (!oldByDay[day]) oldByDay[day] = [];
      oldByDay[day].push(entry);
    }
  }
  // Average old entries per day
  const dailyEntries = Object.entries(oldByDay).sort().map(([day, entries]) => {
    const avg = (field) => entries.reduce((s, e) => s + (e[field] || 0), 0) / entries.length;
    return {
      timestamp: day + 'T12:00:00.000Z',
      totalLoans: avg('totalLoans'),
      fusionBorrowed: avg('fusionBorrowed'),
      fusionCollateral: avg('fusionCollateral'),
      sharePercent: avg('sharePercent'),
      vaultCount: entries[entries.length - 1].vaultCount,
    };
  });
  // Trim daily to max
  const trimmedDaily = dailyEntries.length > MAX_DAILY_ENTRIES
    ? dailyEntries.slice(dailyEntries.length - MAX_DAILY_ENTRIES)
    : dailyEntries;
  history = [...trimmedDaily, ...recent];

  fs.writeFileSync(HISTORY_FILE, JSON.stringify(history, null, 2));
  console.log(`  Saved to ${HISTORY_FILE} (${history.length} entries)`);

  logEntry.historyEntries = history.length;
  appendLog(logEntry);
  console.log(`  Log appended to ${LOGS_FILE}`);
}

collect().catch(err => {
  console.error('Collection failed:', err.message);
  appendLog({ level: 'error', event: 'collect_crash', message: err.message, stack: err.stack });
  process.exit(1);
});
